### ISSUE TITLE
fabric 在python 3.6.3下无法运行

### ISSUE THREAD

**Issue by ghostlyman** [tankywoo/simiki#109]
`ModuleNotFoundError: No module named 'fabric'`

尝试在3.5.3下面运行依旧失败。

**Comment by ghostlyman** [comment]
奇怪 2.7.13 的也不行，还是因为我用了pyenv？
```
(env2.7.13_simiki) xhxu-mac:simiki xhxu$ fab
Traceback (most recent call last):
  File "/Users/xhxu/.pyenv/versions/env2.7.13_simiki/bin/fab", line 11, in <module>
    sys.exit(program.run())
  File "/Users/xhxu/.pyenv/versions/2.7.13/envs/env2.7.13_simiki/lib/python2.7/site-packages/invoke/program.py", line 321, in run
    self.parse_collection()
  File "/Users/xhxu/.pyenv/versions/2.7.13/envs/env2.7.13_simiki/lib/python2.7/site-packages/invoke/program.py", line 399, in parse_collection
    self.load_collection()
  File "/Users/xhxu/.pyenv/versions/2.7.13/envs/env2.7.13_simiki/lib/python2.7/site-packages/fabric/main.py", line 75, in load_collection
    super(Fab, self).load_collection()
  File "/Users/xhxu/.pyenv/versions/2.7.13/envs/env2.7.13_simiki/lib/python2.7/site-packages/invoke/program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/xhxu/.pyenv/versions/2.7.13/envs/env2.7.13_simiki/lib/python2.7/site-packages/invoke/loader.py", line 75, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/xhxu/simiki/fabfile.py", line 9, in <module>
    from fabric.api import env, local, task, settings
ImportError: No module named api
```

**Comment by tankywoo** [comment]
我使用的 [版本](https://github.com/tankywoo/simiki/blob/master/opt_requirements.txt) 是  `Fabric==1.10.2`，我看现在是 2.x 了，且你装的也是 `fabric==2.1.3`，可以降级到 1.10.2 试试，新版本的 fabric 我还没有看过它的 API 变化。

**Comment by ghostlyman** [comment]
又有别的模块问题
```
ImportError: cannot import name 'isMappingType'
(env3.6.3_simiki) xhxu-mac:simiki xhxu$

ImportError: cannot import name 'isMappingType'
(env3.5.3_simiki) xhxu-mac:simiki xhxu$
```

**Comment by tankywoo** [comment]
1. `isMappingType` 这个问题， Fabric 1.x 不支持 py3.x 😢 ，忘了这茬了。

2. `Crypto` 这个问题，针对 Fabric 1.x 的版本，需要升级下，参考 <https://github.com/fabric/fabric/issues/1460#issuecomment-215873949>，因为 fabric 对 paramiko 的版本依赖限制没有做好，导致 pycrypto 这个库没有安装上，可以升级到 `fabric==1.10.3`

P.S 有点想弃疗 fabric了，这几年的 issues 中，关于它的问题还不少。

**Comment by mymusise** [comment]
同样的问题，`which fab`发现调用的系统环境下的`/usr/local/bin/fab` 
最后我用虚拟环境里的fabric `$VENV/bin/fab -f deploy/deploy deploy` 解决了

应该是系统版本的是python2的版本，然而我实际开发的是python3.7的。
