### ISSUE TITLE
OS X 10.9下启动不能

### ISSUE THREAD

**Issue by siton** [tankywoo/simiki#34]
出错如下：

```
➜  wiki git:(master) simiki
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: paramiko>=1.10
```

**Comment by tankywoo** [comment]
应该是`paramiko`是没有装上, `xcode`装了吗？

另外，你安装simiki的方式是pip? 安装时的日志还有吗？

**Comment by tankywoo** [comment]
参考这篇文档试试：[Fabric installs but doesn’t run!](http://www.fabfile.org/faq.html#fabric-installs-but-doesn-t-run)

以及这个[issue](https://github.com/fabric/fabric/issues/1157)

**Comment by siton** [comment]
谢谢回复~

我的Air是从Pro的TimeMachine备份直接迁移过来的，Xcode装了。

`paramiko==1.15.2`

`sudo pip install -U setuptools  && sudo pip install -U distribute`以后问题解决，感谢！
