### ISSUE TITLE
python2.7.x 正常，3.4.x有问题

### ISSUE THREAD

**Issue by ferstar** [tankywoo/simiki#50]
操作系统：Ubuntu 14.04.3 x64
以下是错误内容：

```
[INFO]: Start generating markdown files.
[INFO]: 84 files generated.
[INFO]: Generate catalog page.
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.5.0-1', 'console_scripts', 'simiki')()
  File "/usr/local/lib/python3.4/dist-packages/simiki-1.5.0_1-py3.4.egg/simiki/cli.py", line 419, in main
    generator.generate()
  File "/usr/local/lib/python3.4/dist-packages/simiki-1.5.0_1-py3.4.egg/simiki/cli.py", line 238, in generate
    self.generate_catalog(self.pages)
  File "/usr/local/lib/python3.4/dist-packages/simiki-1.5.0_1-py3.4.egg/simiki/cli.py", line 270, in generate_catalog
    html = catalog_generator.generate_catalog_html()
  File "/usr/local/lib/python3.4/dist-packages/simiki-1.5.0_1-py3.4.egg/simiki/generators.py", line 293, in generate_catalog_html
    html = self.env.get_template("index.html").render(tpl_vars)
  File "/usr/local/lib/python3.4/dist-packages/Jinja2-2.7.3-py3.4.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.4/dist-packages/Jinja2-2.7.3-py3.4.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/Jinja2-2.7.3-py3.4.egg/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/ferstar/wiki/themes/yasimple/index.html", line 1, in <module>
    {% extends "base.html" %}
  File "/home/ferstar/wiki/themes/yasimple/base.html", line 17, in <module>
    {% block container %}
  File "/home/ferstar/wiki/themes/yasimple/index.html", line 12, in <module>
    {% for category_name, pages in site.structure.iteritems() %}
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'iteritems'

```

**Comment by tankywoo** [comment]
traceback信息显示你用的是Python3.4，不是Python2.7

对于Python3.4，需要把主题的`iteritems`改为`items`，这个是1.5.0版本支持Python3.x后的改动。

**Comment by ferstar** [comment]
哦，我标题没编辑对。现在换 2.7 在用了，非常感谢您的这个 wiki 框架:-)

**Comment by tankywoo** [comment]
@ferstar hi, 我看了下你的网站，你应该在用YASimple，感谢提醒，这个主题我也需要改下以兼容Python3.x，感谢你的支持。

如果没有其它问题，这个issue我就给关闭了？

**Comment by ferstar** [comment]
嗯，昨晚逛知乎看到您的帖子，发现这个挺好用，再次感谢！

**Comment by tankywoo** [comment]
@ferstar 好的，YASimple我也已经修正并推到Github上了。有其它问题的话欢迎提issue或pr。感谢你的支持 :smile:
