### ISSUE TITLE
ImportError: cannot import name TESTS

### ISSUE THREAD

**Issue by xzwc** [tankywoo/simiki#62]
➜  mywiki simiki init
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.5.1', 'console_scripts', 'simiki')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/simiki/cli.py", line 53, in <module>
    from simiki.generators import (PageGenerator, CatalogGenerator, FeedGenerator)
  File "/Library/Python/2.7/site-packages/simiki/generators.py", line 23, in <module>
    from jinja2 import (Environment, FileSystemLoader, TemplateError)
  File "/Library/Python/2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 14, in <module>
    from jinja2.defaults import BLOCK_START_STRING, \
  File "/Library/Python/2.7/site-packages/jinja2/defaults.py", line 32, in <module>
    from jinja2.tests import TESTS as DEFAULT_TESTS
ImportError: cannot import name TESTS

**Comment by tankywoo** [comment]
请确认下你的Jinja2版本是否是`2.7.3`：

    python -c 'import jinja2; print(jinja2.__version__)'

这个报错是Jinja2的错误

**Comment by xzwc** [comment]
This is very strange,I am sure that the jinjia2 version is 2.7.3,I delete the jinjia2 from the directory and reinstall the jinjia2  == 2.7.3,the problem dismiss in the end.

**Comment by tankywoo** [comment]
好的，也可能是Jinja2源码文件被损坏或其它情况。

如果这个问题解决了的话，我就关闭Issue了。 👍

**Comment by xzwc** [comment]
ok,thanks
