### ISSUE TITLE
如果文件名中带括号就会报错，不知道是我哪里设置有误还是什么情况

### ISSUE THREAD

**Issue by xcy396** [tankywoo/simiki#79]
错误如下：
➜  mywiki git:(master) ✗ fab deploy
[localhost] local: which ghp-import > /dev/null 2>&1; echo $?
[localhost] local: ghp-import -p -m "Update output documentation" -r origin -b gh-pages output
Traceback (most recent call last):
  File "/usr/local/bin/ghp-import", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ghp_import.py", line 235, in main
    run_import(git, args[0], opts)
  File "/usr/local/lib/python2.7/site-packages/ghp_import.py", line 179, in run_import
    add_file(pipe, fpath, gpath)
  File "/usr/local/lib/python2.7/site-packages/ghp_import.py", line 137, in add_file
    with open(srcpath, "rb") as handle:
IOError: [Errno 2] No such file or directory: u'output/Git/Git\u57fa\u7840\u77e5\u8bc6\u7cfb\u5217(1).html'

Fatal error: local() encountered an error (return code 1) while executing 'ghp-import -p -m "Update output documentation" -r origin -b gh-pages output'

Aborting.

**Comment by tankywoo** [comment]
你好，请提供以下信息：

* 系统发行版 及 版本
* $SHELL
* locale
* Python版本
* ghp-import版本

目前我这边测试你这种情况无法复现问题。
