### ISSUE TITLE
simiki g 报错

### ISSUE THREAD

**Issue by c1ay** [tankywoo/simiki#89]
python: 3.5
simiki:1.6.0.1
```
[ERROR]: content/intro/gettingstarted.md failed to generate:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/simiki/cli.py", line 303, in generate_multiple_pages
    page_meta = self.generate_single_page(page_generator, _f)
  File "/usr/local/lib/python3.5/dist-packages/simiki/cli.py", line 321, in generate_single_page
    self.include_draft)
  File "/usr/local/lib/python3.5/dist-packages/simiki/generators.py", line 113, in to_html
    self.meta, self.content = self.get_meta_and_content()
  File "/usr/local/lib/python3.5/dist-packages/simiki/generators.py", line 138, in get_meta_and_content
    content = self._parse_markup(content_str)
  File "/usr/local/lib/python3.5/dist-packages/simiki/generators.py", line 239, in _parse_markup
    extensions=markdown_extensions,
  File "/usr/local/lib/python3.5/dist-packages/markdown/__init__.py", line 411, in markdown
    return md.convert(text)
  File "/usr/local/lib/python3.5/dist-packages/markdown/__init__.py", line 295, in convert
    newRoot = treeprocessor.run(root)
  File "/usr/local/lib/python3.5/dist-packages/markdown/extensions/codehilite.py", line 215, in run
    placeholder = self.markdown.htmlStash.store(code.hilite(),
  File "/usr/local/lib/python3.5/dist-packages/markdown/extensions/codehilite.py", line 109, in hilite
    lexer = get_lexer_by_name(self.lang)
  File "/usr/local/lib/python3.5/dist-packages/pygments/lexers/__init__.py", line 77, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/usr/local/lib/python3.5/dist-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 18.1 (/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg), Requirement.parse('setuptools>=18.5'))
```

**Comment by Xuanwo** [comment]
pkg_resources.VersionConflict: (setuptools 18.1 (/usr/local/lib/python3.5/dist-packages/setuptools-18.1-py3.5.egg), Requirement.parse('setuptools>=18.5'))

升级一下 setuptools 即可。

**Comment by c1ay** [comment]
谢谢已解决
