### ISSUE TITLE
无法生成output

### ISSUE THREAD

**Issue by SinnerA** [tankywoo/simiki#95]
Mac平台下，使用typora编辑的md文件，使用simiki g生成output时报错：
```
[DEBUG]: Empty the destination directory
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 9, in <module>
    load_entry_point('simiki==1.6.0.1', 'console_scripts', 'simiki')()
  File "/Library/Python/2.7/site-packages/simiki/cli.py", line 401, in main
    generator.generate(include_draft=args['--draft'])
  File "/Library/Python/2.7/site-packages/simiki/cli.py", line 178, in generate
    self.generate_tags()
  File "/Library/Python/2.7/site-packages/simiki/cli.py", line 214, in generate_tags
    meta, _ = g.get_meta_and_content(do_render=False)
  File "/Library/Python/2.7/site-packages/simiki/generators.py", line 135, in get_meta_and_content
    meta = self.parse_meta(meta_str)
  File "/Library/Python/2.7/site-packages/simiki/generators.py", line 218, in parse_meta
    meta.update({'category': category, 'filename': dst_fname})
AttributeError: 'unicode' object has no attribute 'update'
```

**Comment by SinnerA** [comment]
_config.yml内容：
`url:
title:
keywords:
description:
author:

root: /wiki

debug: True`

**Comment by Xuanwo** [comment]
```
AttributeError: 'unicode' object has no attribute 'update'
```

从报错上来看，应该是typora产生的md文件 front-meta 头不是 yaml 格式的，你可以贴一个 typora 编辑生成的文件内容看看。

**Comment by SinnerA** [comment]
果然是这个原因，感谢~
之前的冒号后少了空格...
```
---
title:测试
date:2017-05-12
---

[TOC]

### 测试
```
