### ISSUE TITLE
写了个dockerfile但build的时候报错了

### ISSUE THREAD

**Issue by callect** [tankywoo/simiki#98]
想把simiki做成docker镜像，但是build的过程中出错了
```
Traceback (most recent call last):
  File "/usr/local/bin/simiki", line 11, in <module>
    load_entry_point('simiki==1.6.2.1', 'console_scripts', 'simiki')()
  File "/usr/local/lib/python3.6/site-packages/simiki/cli.py", line 404, in main
    generator.generate(include_draft=args['--draft'])
  File "/usr/local/lib/python3.6/site-packages/simiki/cli.py", line 181, in generate
    self.generate_tags()
  File "/usr/local/lib/python3.6/site-packages/simiki/cli.py", line 206, in generate_tags
    g = PageGenerator(self.config, self.target_path)
  File "/usr/local/lib/python3.6/site-packages/simiki/generators.py", line 95, in __init__
    super(PageGenerator, self).__init__(site_config, base_path)
  File "/usr/local/lib/python3.6/site-packages/simiki/generators.py", line 43, in __init__
    self.site_config = copy.deepcopy(site_config)
  File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/usr/local/lib/python3.6/copy.py", line 273, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/usr/local/lib/python3.6/site-packages/pytz/__init__.py", line 286, in _p
    return unpickler(*args)
  File "/usr/local/lib/python3.6/site-packages/pytz/tzinfo.py", line 526, in unpickler
    tz = pytz.timezone(zone)
  File "/usr/local/lib/python3.6/site-packages/pytz/__init__.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'local'
```
dockerfile是这样的，麻烦帮看下是什么问题
```
FROM daocloud.io/library/python:3.6.0-alpine

RUN pip install simiki && \
    mkdir -p /var/www/wiki-esc
WORKDIR /var/www/wiki-esc

RUN echo y | simiki init && \
    simiki g

CMD ["simiki", "p"]
```

**Comment by Xuanwo** [comment]
从报错上看，可能是环境中没有正确设置时区。

**Comment by tankywoo** [comment]
@callect 两个解决办法，Dockerfile 加上以下任意一条指令：

```
ENV TZ=Asia/Shanghai
```

或者

```
RUN echo "Asia/Shanghai" > /etc/timezone
```
---
具体分析：python:3.6.0-alpine 只有 `/etc/localtime`，且不是软链，没有 `/etc/timezone` 等文件。按照 simiki 使用的其中一个时区库 `tzlocal`，逻辑上是先解析 `TZ` 环境变量，没有则检查 `/etc/timezone` 时区文件，再没有则检查软链接的 `/etc/timezone`等等，最后都不符合则 zone 就是 `local`，导致 `pytz` 库无法解析这个 zone 名。

刚去 `tzlocal` issue 上看了下，发现有个一样的问题，https://github.com/regebro/tzlocal/issues/44

**Comment by callect** [comment]
果然可以，谢谢！

**Comment by tankywoo** [comment]
@callect 恩，后续有问题欢迎随时提 Issue，这个我先关闭了。
